// Lexer.cpp generated by reflex 6.0.0 from lexer.l

#define REFLEX_VERSION "6.0.0"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define REFLEX_OPTION_YYLTYPE             ExprParser::location
#define REFLEX_OPTION_YYSTYPE             ExprParser::Parser::semantic_type
#define REFLEX_OPTION_bison               true
#define REFLEX_OPTION_bison_cc            true
#define REFLEX_OPTION_bison_cc_namespace  ExprParser
#define REFLEX_OPTION_bison_cc_parser     Parser
#define REFLEX_OPTION_header_file         "Lexer.hpp"
#define REFLEX_OPTION_lex                 nextToken
#define REFLEX_OPTION_lexer               SampleLexer
#define REFLEX_OPTION_outfile             "Lexer.cpp"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %top user code                                                 //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 7 "lexer.l"

#include <string>
#include <iostream>
#include "Parser.hpp"


////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS INCLUDE                                                       //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include "Lexer.hpp"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  BISON C++                                                                 //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////


////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

int SampleLexer::nextToken(ExprParser::Parser::semantic_type& yylval)
{
  static const char *REGEX_INITIAL = "(?m)([0-9]+)|([A-Z_a-z][0-9A-Z_a-z]*)|((?:\\Q+\\E))|((?:\\Q-\\E))|((?:\\Q*\\E))|((?:\\Q/\\E))|((?:\\Q%\\E))|((?:\\Q(\\E))|((?:\\Q)\\E))|([\\x09\\x0a\\x0d\\x20]+)|(.)";
  static const reflex::Pattern PATTERN_INITIAL(REGEX_INITIAL);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
  }
  while (true)
  {
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
              return int();
            }
            else
            {
              out().put(matcher().input());
            }
            break;
          case 1: // rule lexer.l:15: [0-9]+ :
#line 15 "lexer.l"
{
    std::cout << "Número detectado: " << str() << std::endl;
    return ExprParser::Parser::token::NUMBER;
}

            break;
          case 2: // rule lexer.l:20: [a-zA-Z_][a-zA-Z0-9_]* :
#line 20 "lexer.l"
{
    std::cout << "Identificador detectado: " << str() << std::endl;
    return ExprParser::Parser::token::IDENTIFIER;
}

            break;
          case 3: // rule lexer.l:25: "+" :
#line 25 "lexer.l"
{ return ExprParser::Parser::token::OP_PLUS; }
            break;
          case 4: // rule lexer.l:26: "-" :
#line 26 "lexer.l"
{ return ExprParser::Parser::token::OP_MINUS; }
            break;
          case 5: // rule lexer.l:27: "*" :
#line 27 "lexer.l"
{ return ExprParser::Parser::token::OP_MULT; }
            break;
          case 6: // rule lexer.l:28: "/" :
#line 28 "lexer.l"
{ return ExprParser::Parser::token::OP_DIV; }
            break;
          case 7: // rule lexer.l:29: "%" :
#line 29 "lexer.l"
{ return ExprParser::Parser::token::OP_MOD; }
            break;
          case 8: // rule lexer.l:30: "(" :
#line 30 "lexer.l"
{ return ExprParser::Parser::token::OPEN_PAR; }
            break;
          case 9: // rule lexer.l:31: ")" :
#line 31 "lexer.l"
{ return ExprParser::Parser::token::CLOSE_PAR; }
            break;
          case 10: // rule lexer.l:32: [ \t\n\r]+ :
#line 32 "lexer.l"
{ /* ignorar espacios */ }

            break;
          case 11: // rule lexer.l:34: . :
#line 34 "lexer.l"
{
    std::cerr << "Carácter no reconocido: " << str() << std::endl;
    return -1;
}

            break;
        }
  }
}
