// Lexer.hpp generated by reflex 6.0.0 from lexer.l

#ifndef REFLEX_LEXER_HPP
#define REFLEX_LEXER_HPP
#define IN_HEADER 1
#define REFLEX_VERSION "6.0.0"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define REFLEX_OPTION_fast                true
#define REFLEX_OPTION_header_file         "Lexer.hpp"
#define REFLEX_OPTION_lex                 nextToken
#define REFLEX_OPTION_lexer               SampleLexer
#define REFLEX_OPTION_outfile             "Lexer.cpp"
#define REFLEX_OPTION_token_type          Tokens

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %top user code                                                 //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 13 "lexer.l"

    #include "tokens.hpp"


////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/matcher.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  ABSTRACT LEXER CLASS                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/abslexer.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

class SampleLexer : public reflex::AbstractLexer<reflex::Matcher> {
#line 17 "lexer.l"

    // aqui podemos agregarle mas metodos a lexer, por defecto son private
public:
  //  std::string tokenText; // este es un ejemplo, no hace nada

 public:
  typedef reflex::AbstractLexer<reflex::Matcher> AbstractBaseLexer;
  SampleLexer(
      // a persistent source of input, empty by default
      const reflex::Input& input = reflex::Input(),
      // optional output stream, std::cout by default
      std::ostream& os = std::cout)
    :
      AbstractBaseLexer(input, os)
  {
  }
  static const int INITIAL = 0;
  // the lexer function defined by SECTION 2
  virtual Tokens nextToken(void);
  // lexer functions accepting new input to scan
  Tokens nextToken(const reflex::Input& input)
  {
    in(input);
    return nextToken();
  }
  Tokens nextToken(const reflex::Input& input, std::ostream *os)
  {
    in(input);
    if (os)
      out(*os);
    return nextToken();
  }
};

#endif
