// Lexer.cpp generated by reflex 6.0.0 from lexer.l

#define REFLEX_VERSION "6.0.0"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define REFLEX_OPTION_fast                true
#define REFLEX_OPTION_header_file         "Lexer.hpp"
#define REFLEX_OPTION_lex                 nextToken
#define REFLEX_OPTION_lexer               SampleLexer
#define REFLEX_OPTION_outfile             "Lexer.cpp"
#define REFLEX_OPTION_token_type          Tokens

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %top user code                                                 //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 13 "lexer.l"

    #include "tokens.hpp"


////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS INCLUDE                                                       //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include "Lexer.hpp"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %{ user code %}                                                //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 1 "lexer.l"
// para llamar a la clase SampleLexer en ves de Lexer
#line 3 "lexer.l"
//metodo nextToken envez de lex()
#line 5 "lexer.l"
// sirve para que se pueda usar definir el tipo de retorno como Tokens con un enum class
#line 8 "lexer.l"
//esto va al cpp
/*%{
#include "tokens.hpp"
%}*/
 // esto aparce en el hpp

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

extern void reflex_code_INITIAL(reflex::Matcher&);

Tokens SampleLexer::nextToken(void)
{
  static const reflex::Pattern PATTERN_INITIAL(reflex_code_INITIAL);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
  }
  while (true)
  {
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
#line 27 "lexer.l"
return Tokens::END_OF_FILE;// cuando usemos bison si se definira como 0
            }
            else
            {
              out().put(matcher().input());
            }
            break;
          case 1: // rule lexer.l:23: [a-zA-Z_][a-zA-Z0-9_]* :
#line 23 "lexer.l"
return Tokens::ASCII_IDENTIFIER;
            break;
          case 2: // rule lexer.l:24: [0-9]+ :
#line 24 "lexer.l"
return Tokens::CONST_NUMBER;
            break;
          case 3: // rule lexer.l:25: \"([^\\"]|\\\")*\" :
#line 25 "lexer.l"
return Tokens::CONST_STRING;
            break;
          case 4: // rule lexer.l:26: [ \t\r\n]+ :
#line 26 "lexer.l"
/* no action: ignore all white space */
            break;
        }
  }
}

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  TABLES                                                                    //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/matcher.h>

#if defined(OS_WIN)
#pragma warning(disable:4101 4102)
#elif defined(__GNUC__)
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wunused-label"
#elif defined(__clang__)
#pragma clang diagnostic ignored "-Wunused-variable"
#pragma clang diagnostic ignored "-Wunused-label"
#endif

void reflex_code_INITIAL(reflex::Matcher& m)
{
  int c = 0;
  m.FSM_INIT(c);

S0:
  m.FSM_FIND();
  c = m.FSM_CHAR();
  if ('a' <= c && c <= 'z') goto S9;
  if (c == '_') goto S9;
  if ('A' <= c && c <= 'Z') goto S9;
  if ('0' <= c && c <= '9') goto S15;
  if (c == '"') goto S18;
  if (c == ' ') goto S21;
  if (c == '\r') goto S21;
  if ('\t' <= c && c <= '\n') goto S21;
  return m.FSM_HALT(c);

S9:
  m.FSM_TAKE(1);
  c = m.FSM_CHAR();
  if ('a' <= c && c <= 'z') goto S9;
  if (c == '_') goto S9;
  if ('A' <= c && c <= 'Z') goto S9;
  if ('0' <= c && c <= '9') goto S9;
  return m.FSM_HALT(c);

S15:
  m.FSM_TAKE(2);
  c = m.FSM_CHAR();
  if ('0' <= c && c <= '9') goto S15;
  return m.FSM_HALT(c);

S18:
  c = m.FSM_CHAR();
  if (c == '\\') goto S26;
  if (c == '"') goto S28;
  if (0 <= c) goto S18;
  return m.FSM_HALT(c);

S21:
  m.FSM_TAKE(4);
  c = m.FSM_CHAR();
  if (c == ' ') goto S21;
  if (c == '\r') goto S21;
  if ('\t' <= c && c <= '\n') goto S21;
  return m.FSM_HALT(c);

S26:
  c = m.FSM_CHAR();
  if (c == '"') goto S18;
  return m.FSM_HALT(c);

S28:
  m.FSM_TAKE(3);
  return m.FSM_HALT();
}

