// lex.yy.cpp generated by reflex 6.0.0 from lexer.l

#define REFLEX_VERSION "6.0.0"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define REFLEX_OPTION_bison               true
#define REFLEX_OPTION_header_file         "Lexer.hpp"
#define REFLEX_OPTION_lex                 nextToken
#define REFLEX_OPTION_lexer               SampleLexer
#define REFLEX_OPTION_outfile             "lex.yy.cpp"
#define REFLEX_OPTION_token_type          int

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %top user code                                                 //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 5 "lexer.l"

    #include "Parser.hpp"


////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS INCLUDE                                                       //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include "Lexer.hpp"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  BISON                                                                     //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

SampleLexer YY_SCANNER;

#ifndef YY_EXTERN_C
#define YY_EXTERN_C
#endif

YY_EXTERN_C int yylex(void)
{
  return YY_SCANNER.nextToken();
}

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

int SampleLexer::nextToken(void)
{
  static const char *REGEX_INITIAL = "(?m)(\\+)|(\\*)|(\\()|(\\))|([A-Z_a-z][0-9A-Z_a-z]*)|([0-9]+)|(\"(?:[^\"\\x5c]|\\\\.)*\")|([\\x09\\x0a\\x0d\\x20]+)|(.)";
  static const reflex::Pattern PATTERN_INITIAL(REGEX_INITIAL);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
  }
  while (true)
  {
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
#line 22 "lexer.l"
return Expr::Parser::token::TOK_END_OF_FILE;

            }
            else
            {
              out().put(matcher().input());
            }
            break;
          case 1: // rule lexer.l:10: \+ :
#line 10 "lexer.l"
return Expr::Parser::token::TOK_OP_PLUS;
            break;
          case 2: // rule lexer.l:11: \* :
#line 11 "lexer.l"
return Expr::Parser::token::TOK_OP_MULT;

            break;
          case 3: // rule lexer.l:13: \( :
#line 13 "lexer.l"
return Expr::Parser::token::TOK_OPEN_PAR;
            break;
          case 4: // rule lexer.l:14: \) :
#line 14 "lexer.l"
return Expr::Parser::token::TOK_CLOSE_PAR;

            break;
          case 5: // rule lexer.l:16: [a-zA-Z_][a-zA-Z0-9_]* :
#line 16 "lexer.l"
return Expr::Parser::token::TOK_ASCII_IDENTIFIER;
            break;
          case 6: // rule lexer.l:17: [0-9]+ :
#line 17 "lexer.l"
return Expr::Parser::token::TOK_CONST_NUMBER;
            break;
          case 7: // rule lexer.l:18: \"([^\\"]|\\.)*\" :
#line 18 "lexer.l"
return Expr::Parser::token::TOK_CONST_STRING;

            break;
          case 8: // rule lexer.l:20: [ \t\r\n]+ :
#line 20 "lexer.l"
/* ignore whitespace */

            break;
          case 9: // rule lexer.l:24: . :
#line 24 "lexer.l"
{
                            std::cerr << "Unexpected character: " << text() << "\n";
                            return -1;
                        }
            break;
        }
  }
}
